include:
  - project: 'infrastructure/gitlab-ci'
    ref: main
    file: '/templates/cloudbuild-common.gitlab-ci.yaml'
  - project: 'infrastructure/gitlab-ci'
    ref: main
    file: 'templates/deploy.gitlab-ci.yaml'

stages:
  - cloudbuild
  - deploy

cloudbuild:image:prod:
  only:
    - docs
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod:
  only:
    - docs
  except:
    - tags
  extends: .deploy
  environment:
    name: prod
    on_stop: stop:prod

stop:prod:
  only:
    - docs
  except:
    - tags
  extends: .stop
  environment:
    name: prod
